version: '3.8'

services:
  web:
    container_name: slack_channel_summariser
    build:
      context: .
      dockerfile: Dockerfile 
    expose:
      - 8000
    ports:
      - '8000:8000'
    env_file:
      - .env.sample
    volumes:
      - .:/usr/src/app

